server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boke?serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    username: root
  application:
    name: bokeservice
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

